questions_multiple_answers = {
1:("First floor use", "How good is the ground floor use of the buildings on the street in the image?", "Görseldeki sokaktaki binaların zemin kat kullanımını değerlendiriniz?", True),
2:("Proportion first floor with windows", "Is the proportion of the first floor windows of the buildings on the street sufficient in the image?", "Görseldeki cadde binalarının zemin katlarındaki pencere oranını yeterlilik açısından değerlendiriniz", True),
3:("Pavement Qualities", "How is the pavement quality (damage condition, continuity, width, etc.) of the street in the image?", "Görseldeki sokağın kaldırım kalitesini (hasar durumu, eni vs) değerlendiriniz", True),
4:("Scenery (Landscape, natural)", "Is the street in the image sufficient in terms of scenery, landscape and naturalness?", "Görseldeki sokağı; manzara ve peyzaj açısından değerlendiriniz", True),
5:("Pavement Continuity", "How is the continuity of the pavements on the street in the image?", "Görseldeki sokakta kaldırımların sürekliliği(kesintisizliği) nasıldır?", True),
6:("Street Linkage", "Is the linkage of the street in the image with other streets sufficient?", "Görseldeki sokağın diğer sokaklarla bağlantısını yeterlilik açısından değerlendiriniz", True),
7:("Building Scale", "Is the scale of the buildings on the street in the image compatible with the street?", "Görseldeki sokakta binaların ölçeği ile insan ölçeği arasındaki uyumu değerlendiriniz", True),
8:("Proportion Street Wall", "What is the proportion of the street wall in the image?", "Görüntüdeki sokak bina bloğunun kesintisiz uzunluğunu değerlendiriniz", True),
9:("Proportion Sky Across", "How much can you view the sky on the street in the image?", "Görseldeki sokakta gökyüzünü ne kadar görüntüleye biliyorsunuz?", True),
10:("Street Width", "Is the width of the street in the image sufficient?", "Görseldeki sokağın genişliği sizce yeterli midir? ", True),
11:("Vividness", "How vivid is the street in the image?", "Görüntüdeki sokağı canlı/yaşayan ve dinamik olması bakımından değerlendiriniz", True),
12:("Damaged Building", "What is the density of the damaged building on the street in the image?", "Görseldeki sokakta hasarlı yapı yoğunluğu ne kadardır?", False),
13:("Human Population", "Is the street in the image sufficient in terms of human density?", "Görseldeki caddede insan yoğunluğu nasıldır?", False),
14:("Car parking", "What is the density of cars parked on the street in the image?", "Görseldeki sokakta park halindeki araba yoğunluğu nasıldır?", False),
15:("All Street Furniture", "Does the street in the image have enough urban furniture?", "Görseldeki sokak, yeterli kent mobilyasına sahip midir?", False),
16:("Small Planters", "Is the density of small plants on the street in the image sufficient?", "Görseldeki sokakta küçük bitkilerin oranı nedir", False),
17:("Historical Buildings", "Are there historical buildings on the street in the image?", "Görseldeki sokakta tarihi binalar bulunmakta mıdır?", False),
18:("Contemporary building", "Are there contemporary buildings on the street in the image?", "Görseldeki sokakta çağdaş binalar var mıdır?", False),
19:("Urban Features (Courtyards/Plazas/Park)", "To what extent does the street in the image have urban features (Courtyards/Plazas/Park)?", "Görseldeki sokak kentsel özelliklere (Avlular/Plazalar/Park) ne ölçüde sahiptir?", False),
20:("Greenness", "Does the street in the image have enough greenery?", "Görseldeki sokakta yeşil oranı nasıldır", False),
21:("Accent Colour", "How intense are the accent colors on the street in the image?", "Resimde sokaktaki ön plana çıkan ve dikkat çeken renkli unsurların varlığını değerlendiriniz", False),
22:("Public space usage", "Is the available public space on the street in the image sufficient?", "Görseldeki sokakta kullanılabilir kamusal alan yeterli midir?", False),
23:("Community", "Evaluate the density of people interacting and spending time in the open area on the street in the image.", "Görseldeki sokakta açık alanda etkileşimde olan ve vakit geçiren insan yoğunluğunu değerlendiriniz?", False),
24:("Traffic Volume", "What is the traffic volume on the street in the image?", "Görselde cadde üzerindeki trafik yoğunluğunu değerlendiriniz", False)
}
q_list = list(questions_multiple_answers.values())