range_questions = [
    ("Unpleasant", "Pleasant"),
    ("Boring", "Interesting"),
    ("Ugly", "Beautiful"),
    ("Strange", "Normal"),
    ("Arousing", "Calm"),
    ("Narrow", "Spacious"),
    ("Dark", "Bright"),
    ("Enclosed", "Open"),
    ("Caotic", "Simple"),
    ("Unsafe", "Safe"),
    ("Not Walkable", 'Walkable'),
]

negative_tags = [(False, 'Graffiti'),
                 (True, 'Narrow'),
                 (False, 'Human'),
                 (True, 'Rubbish'),
                 (False, 'Traffic'),
                 (True, 'Stray Animal'),
                 (False, 'Lack of pavement'),
                 (True, 'Ruin'),
                 (False, 'Dark'),
                 (True, 'Lamp Post'),
                 (False, 'Obstacle'),
                 (True, 'Deserted'),
                 (False, 'Car')]
positive_tags = [(False, 'Tree'),
                 (True, 'Scenery'),
                 (False, 'Seaside/Waterways'),
                 (True, 'Human'),
                 (False, 'Landmark'),
                 (True, 'Street furniture'),
                 (False, 'Accent Colour'),
                 (True, 'Cultural Heritage'),
                 (False, 'Cultural Facilities'),
                 (True, 'Home'),
                 (False, 'Cafe/Restaurant'),
                 (True, 'Bright'),
                 (False, 'Shop/Market'),
                 (True, 'Landscape'),
                 (False, 'Animals'),
                 (True, 'Flower'),
                 (False, 'Public art')]

questions_multiple_answers = {1: ['Birinci kat kullanımı',
                                  'How good is the ground floor use of the buildings on the street in the image?',
                                  'Görseldeki sokaktaki binaların zemin kat kullanımını değerlendiriniz?',
                                  True,
                                  1],
                              2: ['Zemin kat cam yeterliliği',
                                  'Is the proportion of the first floor windows of the buildings on the street sufficient in the image?',
                                  'Görseldeki cadde binalarının zemin katlarındaki pencere oranını yeterlilik açısından değerlendiriniz',
                                  True,
                                  2],
                              3: ['Kaldırım Kalitesi',
                                  'How is the pavement quality (damage condition, continuity, width, etc.) of the street in the image?',
                                  'Görseldeki sokağın kaldırım kalitesini (hasar durumu, eni vs) değerlendiriniz',
                                  True,
                                  3],
                              4: ['Manzara ve Peyzaj',
                                  'Is the street in the image sufficient in terms of scenery, landscape and naturalness?',
                                  'Görseldeki sokağı; manzara ve peyzaj açısından değerlendiriniz',
                                  True,
                                  4],
                              5: ['Kaldırımların Sürekliliği(Kesintisizliği)',
                                  'How is the continuity of the pavements on the street in the image?',
                                  'Görseldeki sokakta kaldırımların sürekliliği(kesintisizliği) nasıldır?',
                                  True,
                                  5],
                              6: ['Sokaklar Arası Bağlantılar',
                                  'Is the linkage of the street in the image with other streets sufficient?',
                                  'Görseldeki sokağın diğer sokaklarla bağlantısını yeterlilik açısından değerlendiriniz',
                                  True,
                                  6],
                              7: ['Bina Ölçeği',
                                  'Is the scale of the buildings on the street in the image compatible with the street?',
                                  'Görseldeki sokakta binaların ölçeği ile insan ölçeği arasındaki uyumu değerlendiriniz',
                                  True,
                                  7],
                              8: ['Orantılı Sokak Duvarı',
                                  'What is the proportion of the street wall in the image?',
                                  'Görüntüdeki sokak bina bloğunun kesintisiz uzunluğunu değerlendiriniz',
                                  True,
                                  8],
                              9: ['Gökyüzü Oranı',
                                  'How much can you view the sky on the street in the image?',
                                  'Görseldeki sokakta gökyüzünü ne kadar görüntüleye biliyorsunuz?',
                                  True,
                                  9],
                              10: ['Cadde Genişliği',
                                   'Is the width of the street in the image sufficient?',
                                   'Görseldeki sokağın genişliği sizce yeterli midir? ',
                                   True,
                                   10],
                              11: ['Canlılık',
                                   'How vivid is the street in the image?',
                                   'Görüntüdeki sokağı canlı/yaşayan ve dinamik olması bakımından değerlendiriniz',
                                   True,
                                   11],
                              12: ['Hasarlı Yapı Yoğunluğu',
                                   'What is the density of the damaged building on the street in the image?',
                                   'Görseldeki sokakta hasarlı yapı yoğunluğu ne kadardır?',
                                   False,
                                   12],
                              13: ['İnsan Yoğunluğu',
                                   'Is the street in the image sufficient in terms of human density?',
                                   'Görseldeki caddede insan yoğunluğu nasıldır?',
                                   False,
                                   13],
                              14: ['Park halindeki arabalar',
                                   'What is the density of cars parked on the street in the image?',
                                   'Görseldeki sokakta park halindeki araba yoğunluğu nasıldır?',
                                   False,
                                   14],
                              15: ['Kent Mobilyası Oranı',
                                   'Does the street in the image have enough urban furniture?',
                                   'Görseldeki sokak, yeterli kent mobilyasına sahip midir?',
                                   False,
                                   15],
                              16: ['Küçük Bitkiler',
                                   'Is the density of small plants on the street in the image sufficient?',
                                   'Görseldeki sokakta küçük bitkilerin oranı nedir',
                                   False,
                                   16],
                              17: ['Tarihi Binalar',
                                   'Are there historical buildings on the street in the image?',
                                   'Görseldeki sokakta tarihi binalar bulunmakta mıdır?',
                                   False,
                                   17],
                              18: ['Çağdaş Binalar',
                                   'Are there contemporary buildings on the street in the image?',
                                   'Görseldeki sokakta çağdaş binalar var mıdır?',
                                   False,
                                   18],
                              19: ['Kentsel Özellikler (Courtyards/Plazas/Park)',
                                   'To what extent does the street in the image have urban features (Courtyards/Plazas/Park)?',
                                   'Görseldeki sokak kentsel özelliklere (Avlular/Plazalar/Park) ne ölçüde sahiptir?',
                                   False,
                                   19],
                              20: ['Yeşillik',
                                   'Does the street in the image have enough greenery?',
                                   'Görseldeki sokakta yeşil oranı nasıldır',
                                   False,
                                   20],
                              21: ['Ön Plandaki Renkli Unsurlar',
                                   'How intense are the accent colors on the street in the image?',
                                   'Resimde sokaktaki ön plana çıkan ve dikkat çeken renkli unsurların varlığını değerlendiriniz',
                                   False,
                                   21],
                              22: ['Kamusal Alan',
                                   'Is the available public space on the street in the image sufficient?',
                                   'Görseldeki sokakta kullanılabilir kamusal alan yeterli midir?',
                                   False,
                                   22],
                              23: ['Topluluk',
                                   'Evaluate the density of people interacting and spending time in the open area on the street in the image.',
                                   'Görseldeki sokakta açık alanda etkileşimde olan ve vakit geçiren insan yoğunluğunu değerlendiriniz?',
                                   False,
                                   23],
                              24: ['Trafik Yoğunluğu',
                                   'What is the traffic volume on the street in the image?',
                                   'Görselde cadde üzerindeki trafik yoğunluğunu değerlendiriniz',
                                   False,
                                   24]}