range_questions = [
    ("Unpleasant", "Pleasant", "Hoş olmayan", "Hoş"),
    ("Boring", "Interesting", "Sıkıcı", "İlgi Çekici"),
    ("Ugly", "Beautiful", "Çirkin", "Güzel"),
    ("Strange", "Normal", "Tuhaf", "Normal"),
    ("Calm", "Arousing", "Sakin", "Canlı"),
    ("Narrow", "Spacious", "Sıkışık", "Ferah"),
    ("Dark", "Bright", "Karanlık", "Aydınlık"),
    ("Enclosed", "Open", "Kapalı", "Açık"),
    ("Caotic", "Simple", "Karmaşık", "Sade"),
    ("Unsafe", "Safe", "Güvenilir Değil", "Güvenilir"),
]

negative_tags = [
    (False, "Graffiti", "Sokak sanatı"),
    (True, "Narrow", "Sıkışık"),
    (False, "Human", "İnsan"),
    (True, "Rubbish", "Çöp/çamur"),
    (False, "Traffic", "Trafik"),
    (True, "Stray Animal", "Başıboş hayvan"),
    (False, "Lack of pavement", "Kaldırım yok"),
    (True, "Ruin", "Yıkıntı"),
    (False, "Dark", "Karanlık"),
    (True, "Lamp Post", "Elektrik direği"),
    (False, "Obstacle", "Engel"),
    (True, "Non-Aesthetic Building", "Estetik Olmayan Bina"),
    (True, "Non-Aesthetic Building Component", "Estetik Olmayan Bina Öğesi"),
    (False, "Car", "Araba"),
    (True, "Other", "Diğer"),
    (False, "Bad-Road Pavement", "Kötü-yol Kaldırım"),
    (False, "Restrictive Component", "Sınırlayıcı Eleman"),
    (False, "Traffic Sign", "Tabela"),
]
positive_tags = [
    (False, "Tree", "Ağaç"),
    (True, "Scenery", "Manzara"),
    (False, "Seaside/Waterways", "Deniz/kanal"),
    (True, "Human", "İnsan"),
    (False, "Landmark", "Kilise"),
    (True, "Street furniture", "Sokak mobilyası"),
    (False, "Accent Colour", "Renkli duvar"),
    (True, "Cultural Heritage", "Kültürel miras"),
    (False, "Cultural Facilities", "Kültürel Yapılar"),
    (True, "Home", "Ev"),
    (False, "Cafe/Restaurant", "Kafe/restoran"),
    (True, "Bright", "Aydınlık"),
    (False, "Shop/Market", "Ticaret"),
    (True, "Landscape", "Park Bahçe"),
    (False, "Animals", "Hayvanlar"),
    (True, "Flower", "Çiçek"),
    (False, "Public art", "Sokak Sanatı"),
    (True, "Other", "Diğer"),
    (False, "Descriptive Component", "Sınırlayı Eleman"),
    (True, "Aesthetic Building Part", "Estetik Bina Ögesi"),
    (False, "Aesthetic Building", "Estetik Bina"),
    (True, "Aesthetic Pavement", "Estetik Yol Kaldırım"),
    (False, "Other Greenery", "Diğer Yeşil"),
    (True, "Iconic Component", "İkonik (Simgesel) Eleman"),
    (False, "Mosque", "Camii"),
]

questions_multiple_answers = {
    1: [
        "Birinci kat kullanımı",
        "How good is the ground floor use of the buildings on the street in the image?",
        "Görseldeki sokaktaki binaların zemin kat kullanımını değerlendiriniz?",
        "First floor use",
        True,
        1,
    ],
    2: [
        "Zemin kat cam yeterliliği",
        "Is the proportion of the first floor windows of the buildings on the street sufficient in the image?",
        "Görseldeki cadde binalarının zemin katlarındaki pencere oranını yeterlilik açısından değerlendiriniz",
        "Proportion first floor with windows",
        True,
        2,
    ],
    3: [
        "Kaldırım Kalitesi",
        "How is the pavement quality (damage condition, continuity, width, etc.) of the street in the image?",
        "Görseldeki sokağın kaldırım kalitesini (hasar durumu, eni vs) değerlendiriniz",
        "Pavement Qualities",
        True,
        3,
    ],
    4: [
        "Manzara ve Peyzaj",
        "Is the street in the image sufficient in terms of scenery, landscape and naturalness?",
        "Görseldeki sokağı; manzara ve peyzaj açısından değerlendiriniz",
        "Scenery (Landscape, natural)",
        True,
        4,
    ],
    5: [
        "Kaldırımların Sürekliliği(Kesintisizliği)",
        "How is the continuity of the pavements on the street in the image?",
        "Görseldeki sokakta kaldırımların sürekliliği(kesintisizliği) nasıldır?",
        "Pavement Continuity",
        True,
        5,
    ],
    6: [
        "Sokaklar Arası Bağlantılar",
        "Is the linkage of the street in the image with other streets sufficient?",
        "Görseldeki sokağın diğer sokaklarla bağlantısını yeterlilik açısından değerlendiriniz",
        "Street Linkage",
        True,
        6,
    ],
    7: [
        "Bina Ölçeği",
        "Is the scale of the buildings on the street in the image compatible with the street?",
        "Görseldeki sokakta binaların ölçeği ile insan ölçeği arasındaki uyumu değerlendiriniz",
        "Building Scale",
        True,
        7,
    ],
    8: [
        "Orantılı Sokak Duvarı",
        "What is the proportion of the street wall in the image?",
        "Görüntüdeki sokak bina bloğunun kesintisiz uzunluğunu değerlendiriniz",
        "Proportion Street Wall",
        True,
        8,
    ],
    9: [
        "Gökyüzü Oranı",
        "How much can you view the sky on the street in the image?",
        "Görseldeki sokakta gökyüzünü ne kadar görüntüleye biliyorsunuz?",
        "Proportion Sky Across",
        True,
        9,
    ],
    10: [
        "Cadde Genişliği",
        "Is the width of the street in the image sufficient?",
        "Görseldeki sokağın genişliği sizce yeterli midir? ",
        "Street Width",
        True,
        10,
    ],
    11: [
        "Canlılık",
        "How vivid is the street in the image?",
        "Görüntüdeki sokağı canlı/yaşayan ve dinamik olması bakımından değerlendiriniz",
        "Vividness",
        True,
        11,
    ],
    12: [
        "Hasarlı Yapı Yoğunluğu",
        "What is the density of the damaged building on the street in the image?",
        "Görseldeki sokakta hasarlı yapı yoğunluğu ne kadardır?",
        "Damaged Building",
        False,
        12,
    ],
    13: [
        "İnsan Yoğunluğu",
        "Is the street in the image sufficient in terms of human density?",
        "Görseldeki caddede insan yoğunluğu nasıldır?",
        "Human Population",
        False,
        13,
    ],
    14: [
        "Park halindeki arabalar",
        "What is the density of cars parked on the street in the image?",
        "Görseldeki sokakta park halindeki araba yoğunluğu nasıldır?",
        "Car parking",
        False,
        14,
    ],
    15: [
        "Kent Mobilyası Oranı",
        "Does the street in the image have enough urban furniture?",
        "Görseldeki sokak, yeterli kent mobilyasına sahip midir?",
        "All Street Furniture",
        False,
        15,
    ],
    16: [
        "Küçük Bitkiler",
        "Is the density of small plants on the street in the image sufficient?",
        "Görseldeki sokakta küçük bitkilerin oranı nedir",
        "Small Planters",
        False,
        16,
    ],
    17: [
        "Tarihi Binalar",
        "Are there historical buildings on the street in the image?",
        "Görseldeki sokakta tarihi binalar bulunmakta mıdır?",
        "Historical Buildings",
        False,
        17,
    ],
    18: [
        "Çağdaş Binalar",
        "Are there contemporary buildings on the street in the image?",
        "Görseldeki sokakta çağdaş binalar var mıdır?",
        "Contemporary building",
        False,
        18,
    ],
    19: [
        "Kentsel Özellikler (Avlular/Plazalar/Park)",
        "To what extent does the street in the image have urban features (Courtyards/Plazas/Park)?",
        "Görseldeki sokak kentsel özelliklere (Avlular/Plazalar/Park) ne ölçüde sahiptir?",
        "Urban Features (Courtyards/Plazas/Park)",
        False,
        19,
    ],
    20: [
        "Yeşillik",
        "Does the street in the image have enough greenery?",
        "Görseldeki sokakta yeşil oranı nasıldır",
        "Greenness",
        False,
        20,
    ],
    21: [
        "Ön Plandaki Renkli Unsurlar",
        "How intense are the accent colors on the street in the image?",
        "Resimde sokaktaki ön plana çıkan ve dikkat çeken renkli unsurların varlığını değerlendiriniz",
        "Accent Colour",
        False,
        21,
    ],
    22: [
        "Kamusal Alan",
        "Is the available public space on the street in the image sufficient?",
        "Görseldeki sokakta kullanılabilir kamusal alan yeterli midir?",
        "Public space usage",
        False,
        22,
    ],
    23: [
        "Topluluk",
        "Evaluate the density of people interacting and spending time in the open area on the street in the image.",
        "Görseldeki sokakta açık alanda etkileşimde olan ve vakit geçiren insan yoğunluğunu değerlendiriniz?",
        "Community",
        False,
        23,
    ],
    24: [
        "Trafik Yoğunluğu",
        "What is the traffic volume on the street in the image?",
        "Görselde cadde üzerindeki trafik yoğunluğunu değerlendiriniz",
        "Traffic Volume",
        False,
        24,
    ],
}
